[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/kreta"]

[project]
name = "e-kreta-hun0r"
version = "2.0.1"
authors = [
  { name="hun0r", email="kiskukac1024@gmail.com" },
]
description = "E-KrÃ©ta API wrapper"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/hun0r/e-kreta-hun0r-2.0"
Issues = "https://github.com/hun0r/e-kreta-hun0r-2.0/issues"