[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ditidy"
version = "2.0.4"
authors = [{ name = "Kadir Sevil", email = "kadir.sevil@diodeiot.com" }]
description = "Formatting utility for C"
readme = "README.md"
requires-python = ">=3"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "GPL-3.0-or-later"
license-files = ["LICEN[CS]E*"]
dependencies = ["click>=8.1, <9", "PyYAML>=6, <7", "flake8-import-order"]

[project.urls]
Homepage = "https://github.com/diodeiot/ditidy"
Issues = "https://github.com/diodeiot/ditidy/issues"

[project.scripts]
ditidy = "ditidy.cli:cli"

[tool.hatch.envs.default.scripts]
lint = "flake8 ."
