[tool.poetry]
name = "sovai"
version = "0.2.47"
description = "python for asset management"
authors = ["Derek Snow <d.snow@outlook.com>"]
license = "Proprietary License"
readme = "README.md"
include = ["sovai/**/*", "data/**/*"]
exclude = [
 "notebooks",
 "notebooks/**/*",
 "tests",
 "tests/**/*",
 "docs",
 "docs/**/*",
 ".github",
 ".github/**/*",
 ".venv",
 ".venv/**/*",
 "dist",
 "dist/**/*",
 "*.pyc",
 "**/*.pyc",
 "*.pyo",
 "**/*.pyo",
 "__pycache__",
 "**/__pycache__",
 ".ipynb_checkpoints",
 "**/.ipynb_checkpoints",
]

[tool.poetry.dependencies]
python = "^3.10"
pandas = ">=1.0"
numpy = ">=1.20"
pyarrow = ">=5.0"
requests = ">=2.20"
python-dateutil = ">=2.8"
python-dotenv = ">=0.10"
polars = "^1.2"
boto3 = ">=1.20"
joblib = ">=1.0"
rapidfuzz = "^3.9.7"
edgar-tool = "^1.3.3"
scipy = {version = ">=1.0", optional = true}
matplotlib = {version = ">=3.0", optional = true}
plotly = {version = ">=5.0", optional = true}
scikit-learn = {version = ">=1.0", optional = true}
numba = {version = ">=0.50", optional = true}
dash = {version = ">=2.0", optional = true}
great-tables = {version = ">=0.9", optional = true}
ruptures = {version = ">=1.0", optional = true}
shap = {version = ">=0.40", optional = true}
skfolio = {version = ">=0.3", optional = true}
statsforecast = {version = ">=1.0", optional = true}
tensorly = {version = ">=0.6", optional = true}
openai = {version = ">=1.0", optional = true}
mfles = {version = ">=0.2", optional = true}
pexpect = {version = ">=4.9.0", optional = true}
lightgbm = {version = ">=4.5.0", optional = true}
ipywidgets = {version = ">=8.1.3", optional = true}
polars-talib = {version = "0.1.3", optional = true}
dash-bootstrap-components = {version = ">=1.6.0", optional = true}
yachalk = "^0.1.6"
pyvis = "^0.3.2"
networkx = "^3.3"
seaborn = "^0.13.2"
s3fs = "^2024.10.0"
gcsfs = "^2024.10.0"
fastapi-cache = "^0.1.0"
fastapi-cache2 = {extras = ["redis"], version = "^0.2.1"}


[tool.poetry.extras]
full = [
 "scipy",
 "matplotlib",
 "plotly",
 "scikit-learn",
 "numba",
 "dash",
 "great-tables",
 "ruptures",
 "shap",
 "skfolio",
 "statsforecast",
 "tensorly",
 "openai",
 "mfles",
 "pexpect",
 "lightgbm",
 "ipywidgets",
 "polars-talib",
 "dash-bootstrap-components"
]

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
jinja2 = "^3.1.4"
traitlets = "^5.14.3"
jupyterlab = "^4.2.5"
pytest = "^7.0"
black = "^22.0"


[build-system]
