[project]
name = "odc-stac"
description = "Tooling for converting STAC metadata to ODC data model"
version = "0.4.0rc3"
authors = [
    {name = "Open Data Cube"}
]
maintainers = [
    {name = "Open Data Cube"}
]
readme = "README.rst"
license = {text = "Apache License 2.0"}
requires-python = ">=3.8"
classifiers = [
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Scientific/Engineering :: GIS",
    "Typing :: Typed"
]
dependencies = [
    "affine",
    "odc-geo>=0.4.7",
    "odc-loader>=0.5.1",
    "rasterio>=1.0.0,!=1.3.0,!=1.3.1",
    "dask[array]",
    "numpy>=1.20.0",
    "pandas",
    "pystac>=1.0.0,<2",
    "toolz",
    "xarray>=0.19"
]

[project.optional-dependencies]
botocore = ["botocore"]
docs = [
    "sphinx",
    "sphinx_rtd_theme",
    "nbsphinx",
    "sphinx-autodoc-typehints",
    "matplotlib-inline",
    "pandas",
    "distributed",
    "datacube>=1.8.8",
    "ipython",
    "ipykernel"
]
test = [
    "pytest",
    "pytest-cov",
    "pytest-timeout",
    "pystac_client",
    "distributed",
    "geopandas"
]
test-all = [
    "pytest",
    "pytest-cov",
    "pytest-timeout",
    "pystac_client",
    "distributed",
    "geopandas",
    "datacube",
    "stackstac"
]

[project.urls]
Documentation = "https://odc-stac.readthedocs.io/en/latest/"
"Bug Reporting" = "https://github.com/opendatacube/odc-stac/issues"
Homepage = "https://github.com/opendatacube/odc-stac/"

[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.module]
name = "odc.stac"

[tool.mypy]
python_version = "3.10"
ignore_missing_imports = true
allow_redefinition = true
enable_error_code = ["explicit-override"]
warn_redundant_casts = true
warn_unused_ignores = true
plugins = "numpy.typing.mypy_plugin"
explicit_package_bases = true

[tool.coverage.run]
omit = [
  "tests/*",
  "*/test_*"
]

[tool.isort]
profile = "black"

[tool.pylint.messages_control]
max-line-length = 120
max-args = 15
max-positional-arguments = 12
disable = [
  "missing-function-docstring",
  "invalid-name",
  "fixme",
  "wrong-import-order",
  "duplicate-code",
  "ungrouped-imports",
]
