[project]
name = "yta-google-drive-downloader"
version = "0.0.3"
description = ""
authors = [
    {name = "danialcala94",email = "danielalcalavalera@gmail.com"}
]
readme = "README.md"
requires-python = "==3.9"
dependencies = [
    "yta_general_utils (>=0.0.250,<1.0.0)",
    "lxml (>=5.2.2,<6.0.0)",
    "requests (>=2.32.3,<3.0.0)"
]

[tool.poetry]
packages = [{include = "yta_google_drive_downloader", from = "src"}]


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
