[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "m24842_models"
version = "0.1.17"
description = ""
requires-python = ">=3.8"
dependencies = [
    "torch",
    "einops",
    "opt_einsum",
    "rotary_embedding_torch",
]