[project]
name = "self-code-adk"
version = "0.1.8"
description = "ADK agent which help in analysing currently running multiagent app"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-adk>=0.3.0",
]

keywords = ["adk", "agent", "code-analyzer"]
license = "MIT"
authors = [
  {name = "Marcin <n0npax> Niemira"},
]
maintainers = [
  {name = "Marcin <n0npax> Niemira"},
]

[project.urls]
Homepage = "https://github.com/n0npax/self-code-adk"
Documentation = "https://github.com/n0npax/self-code-adk"
Repository = "https://github.com/n0npax/self-code-adk"

[dependency-groups]
dev = [
    "black>=25.1.0",
    "pytest>=8.3.5",
]

[tool.setuptools.packages.find]
where = ["self_code_adk"]
exclude = ["*_test.py", "*.tests", "*.tests.*"]
