[project]
name = "arbiterx"
version = "0.2.5"
description = ""
authors = [
    {name = "parthokr",email = "partho.kr@proton.me"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "rich (>=13.9.4,<14.0.0)"
]

[tool.poetry]
packages = [{include = "arbiterx", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
