[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pulumi-django-azure"
version = "1.0.32"
description = "Simply deployment of Django on Azure with Pulumi"
readme = "README.md"
authors = [{ name = "Maarten Ureel", email = "maarten@youreal.eu" }]
license = "MIT"
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = ["django", "pulumi", "azure"]
dependencies = [
    "azure-identity (>=1.21.0,<2.0.0)",
    "azure-keyvault-secrets (>=4.9.0,<5.0.0)",
    "azure-mgmt-cdn (>=13.1.1,<14.0.0)",
    "azure-mgmt-resource (>=23.3.0,<24.0.0)",
    "django (>=5.2,<6.0)",
    "django-azure-communication-email (>=1.3.2,<2.0.0)",
    "django-environ (>=0.12.0,<0.13.0)",
    "django-redis (>=5.4.0,<6.0.0)",
    "django-storages[azure] (>=1.14.6,<2.0.0)",
    "pulumi (>=3.165.0)",
    "pulumi-azure-native (>=3.2.0)",
    "pulumi-random (>=4.18.1)",
    "redis[hiredis] (>=5.2.1,<6.0.0)"
]
requires-python = ">=3.11,<3.14"

[project.urls]
Homepage = "https://gitlab.com/MaartenUreel/pulumi-django-azure"

[tool.poetry]
name = "pulumi-django-azure"
version = "1.0.32"
description = "Simplify deployment of Django websites on Azure with Pulumi"
authors = ["Maarten Ureel <maarten@youreal.eu>"]

[tool.poetry.dependencies]
python = "^3.11,<3.14"
azure-identity = "^1.21.0"
azure-keyvault-secrets = "^4.9.0"
azure-mgmt-cdn = "^13.1.1"
azure-mgmt-resource = "^23.3.0"
django = "^5.2"
django-azure-communication-email = "^1.3.2"
django-environ = "^0.12.0"
django-redis = "^5.4.0"
django-storages = {extras = ["azure"], version = "^1.14.6"}
pulumi = ">=3.165.0"
pulumi-azure-native = ">=3.2.0"
pulumi-random = ">=4.18.1"
redis = {extras = ["hiredis"], version = "^5.2.1"}

[tool.poetry.group.dev.dependencies]
build = "^1.2.2.post1"
mkdocs-material = "^9.6.12"
pre-commit = "^4.2.0"
ruff = "^0.11.7"
twine = "^6.1.0"

[tool.ruff]
line-length = 140

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]
