[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "django-enquiries"
version = "0.2"
dependencies = [
    "django>=5.1"
]
description = "A Django app to handle un-authenticated user enquiries via a contuct-us form."
readme = "README.rst"
requires-python = ">= 3.10"
authors = [
    {name = "Egide Ndazimana", email = "egide.n1997@gmail.com"},
]
classifiers = [
    "Environment :: Web Environment",
    "Framework :: Django",
    "Framework :: Django :: 5.1",
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]