[project]
name = "surfmesh"
version = "0.2.12"
description = "A Python library to create simple 3D Surface Meshs using Quadrilateral dominant faces."
readme = "README.md"
authors = [
    { name = "Chaitanya Kesanapalli", email = "7126460+ckesanapalli@users.noreply.github.com" }
]
requires-python = ">=3.10"
dependencies = [
    "numpy>=1.24"
]
classifiers = [
  # How mature is this project? Common values are
  #   3 - Alpha
  #   4 - Beta
  #   5 - Production/Stable
  "Development Status :: 4 - Beta",

  # Indicate who your project is intended for
  "Intended Audience :: Science/Research",
  "License :: OSI Approved :: MIT License",
  "Topic :: Scientific/Engineering",
  "Topic :: Software Development :: Libraries :: Python Modules",


  # Specify the Python versions you support here.
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
]

[project.urls]
Homepage = "https://github.com/ckesanapalli/surfmesh"
GitHub = "https://github.com/ckesanapalli/surfmesh"
Documentation = "https://github.com/ckesanapalli/surfmesh/blob/master/README.md"
Bug = "https://github.com/ckesanapalli/surfmesh/issues"


[project.scripts]
surfmesh = "surfmesh:main"

[project.optional-dependencies]
examples = [
    "ipykernel>=6.29.5",
    "jupyterlab>=4.4.0",
    "matplotlib>=3.10.1"
]
dev = [
    "pytest>=8.3.5",
    "pytest-cov>=6.1.1",
    "ruff>=0.1.6"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
preview = true
line-length = 180
indent-width = 4
target-version = "py311"
exclude = [
    ".bzr", ".direnv", ".eggs", ".git", ".git-rewrite", ".hg", ".ipynb_checkpoints",
    ".mypy_cache", ".nox", ".pants.d", ".pyenv", ".pytest_cache", ".pytype",
    ".ruff_cache", ".svn", ".tox", ".venv", ".vscode", "__pypackages__",
    "_build", "buck-out", "build", "dist", "node_modules", "site-packages", "venv", "tests"
]

[tool.ruff.lint]
select = [
    "F", "E", "C90", "I", "N", "UP", "YTT", "ANN", "ASYNC", "S", "BLE", "B", "A", "C4",
    "DTZ", "T10", "DJ", "EM", "EXE", "FA", "ISC", "ICN", "LOG", "G", "INP", "PIE", "T20",
    "PYI", "PT", "Q", "RSE", "RET", "SLF", "SLOT", "SIM", "TID", "TC", "INT", "ARG", "PTH",
    "TD", "FIX", "PD", "PGH", "TRY", "FLY", "NPY", "FAST", "AIR", "PERF", "FURB", "RUF"
]

ignore = []
fixable = ["ALL"]
unfixable = []
exclude = ["*.ipynb"]
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
extend-select = ["E302", "E303"]

[tool.ruff.format]
quote-style = "double"
exclude = ["*.ipynb"]
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = false
docstring-code-line-length = "dynamic"

