[tool.poetry]
name = "coralsnake"
version = "0.0.43"
description = "Transcriptome mapping utils"
authors = ["Chang Ye <yech1990@gmail.com>"]
readme = "README.md"
license = "GPL-3.0"
keywords = ["transcriptome", "mapping"]
repository = "https://github.com/y9c/coralsnake"

[tool.poetry.dependencies]
python = "^3.10"
dnaio = "^1.2.1"
rich-click = "^1.8.3"
pysam = "^0.22.1"
numpy = "^1.26.4"
ncls = "^0.0.68"
pyfamsa = "^0.4.0"
scipy = "^1.14.0"

[tool.poetry.scripts]
coralsnake = 'coralsnake.cli:cli'

[tool.poetry.group.dev.dependencies]
setuptools = "^70.1.1"

[build-system]
requires = ["poetry-core", "Cython", "setuptools"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.build]
generate-setup-file = false
script = 'build_package.py'
