[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
# Elenco dei pacchetti nel progetto
packages = ["LabToolbox"]

# Indica che i file non Python (come README.md, LICENSE) devono essere inclusi
include-package-data = true

[tool.setuptools.package-data]
# Specifica i file aggiuntivi da includere nel pacchetto
"LabToolbox" = ["README.md", "LICENSE"]

[project]
name = "LabToolbox"
version = "1.1.0"
description = "LabToolbox Ã¨ una raccolta di strumenti per l'analisi e l'elaborazione di dati sperimentali in ambito scientifico."
authors = [
    { name = "Giuseppe Sorrentino", email = "sorrentinogiuse@icloud.com" }
]
readme = "README.md"
dependencies = [
    "numpy",
    "scipy",
    "matplotlib",
    "statsmodels",
    "emcee",
    "corner",
    "lmfit",
]
requires-python = ">= 3.8"
classifiers=[
    'Programming Language :: Python :: 3',
    'Operating System :: OS Independent',
]
license = 'MIT'
license-files = ["LICENSE"]

[project.urls]
Documentation = "https://github.com/giusesorrentino/LabToolbox/wiki"
Source = "https://github.com/giusesorrentino/LabToolbox"
Tracker = "https://github.com/giusesorrentino/LabToolbox/issues"
Changelog = "https://github.com/giusesorrentino/LabToolbox/releases"