[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "psychopy-neuroplaypro-neurolab"
version = "0.0.4"
description = "NeuroPlay EEG recording plugin for PsychoPy Builder"
authors = [{name = "Enicast", email = "enicaster@gmail.com"}]
dependencies = ["psychopy"]
requires-python = ">=3.8"

[project.entry-points."psychopy.plugins"]
neuroplay = "psychopy_neuroplaypro.plugin:NeuroPlayPlugin"

[tool.setuptools]
packages = ["psychopy_neuroplaypro"]
