[project]
name = "pyritex"
version = "0.0.7"
description = "An AnyIO-compatible async Linux Netlink library."
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "anyio>=4.9.0",
    "black>=24.10.0",
    "flake8>=7.1.1",
    "oxitrait>=0.0.1",
    "pydantic>=2.10.5",
    "result>=0.17.0",
    "toolz>=1.0.0",
    "trio>=0.28.0",
]
