[project]
name = "drfx"
version = "0.1.4"
description = "Optimized and performance Django Rest Framework Extensions"
license = { text = "MIT" }
authors = [{ name="Dmitrii", email="you@example.com" }]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "djangorestframework>=3.14",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
[tool.setuptools.packages.find]
include = ["drfx"]
