[project]
name = "trading-strategy-tester"
version = "0.1.0"
description = "Simulate and evaluate trading strategies"
authors = [{ name = "Daniel Å oltÃ½s", email = "danielsytlos@gmail.com" }]
license = "MIT"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "pandas~=2.2.2",
  "numpy~=2.0.1",
  "matplotlib",
  "plotly~=5.23.0",
  "yfinance==0.2.57",
  "ollama~=0.4.7",
  "pandas_ta~=0.3.14b0",
  "deepdiff~=8.4.2"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["trading_strategy_tester*"]
