[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"

[project]
name = "wish-models"
version = "0.6.28"
description = "Models used in wish-sh and RapidPen"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Security & Development Lab", email = "lay.sakura+secdevlab@gmail.com" },
]
maintainers = [
    { name = "Sho Nakatani", email = "lay.sakura@gmail.com" },
]
keywords = [
    "wish",
    "rapidpen",
    "llm",
    "ai",
    "shell",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Software Development :: Libraries",
    "Topic :: System :: Shells",
]
dependencies = [
    "pydantic>=2.10.6",
    "pydantic-settings>=2.0.0",
]

[project.urls]
Homepage = "https://github.com/SecDev-Lab/wish"
Documentation = "https://github.com/SecDev-Lab/wish"
Repository = "https://github.com/SecDev-Lab/wish.git"
Issues = "https://github.com/SecDev-Lab/wish/issues"

[project.license]
file = "../LICENSE"

[tool.uv]
dev-dependencies = [
    "factory-boy>=3.3.1",
    "pytest-asyncio>=0.25.2",
    "pytest>=8.3.4",
    "ruff>=0.9.8",
]

[tool.pdm.build]
includes = [
    "src/",
]

[tool.ruff]
line-length = 120
indent-width = 4

[tool.ruff.lint]
select = [
    "E",
    "F",
    "I",
    "B",
    "W",
]

[tool.pytest.ini_options]
testpaths = [
    "tests",
]
pythonpath = [
    "src",
]
addopts = [
    "--import-mode=importlib",
]
asyncio_default_fixture_loop_scope = "function"
