[project]
name = "timol"
version = "1.2.2"
description = "3D Molecular viewer in the terminal"
readme = "README.md"
authors = [
    { name = "GregoryFonseca", email = "gregorycordeirofonseca@gmail.com" },
]
requires-python = ">=3.9"
dependencies = [
    "importlib-resources>=6.5.2",
    "numpy>=2.0.2",
    "textual>=2.1.2",
    "ase>=3.24.0",
    "scikit-image>=0.24.0",
    "tqdm>=4.67.1",
]
license = "MIT"
license-files = ["LICENSE"]

[project.scripts]
timol = "timol:cli"
timol_bmark = "timol:bmark"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
