[tool.poetry]
name = "pydrifter"
version = "0.1.5-1"
description = "Data drift checking for ML projects"
authors = ["aesedeu <aesedeu@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pandas = "^2.2.3"
scipy = "^1.15.2"
numpy = "^2.2.4"
tabulate = "^0.9.0"
seaborn = "^0.13.2"
pendulum = "^3.0.0"
termcolor = "^3.0.1"
scikit-learn = "^1.6.1"
tqdm = "^4.67.1"
ipywidgets = "^8.1.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[project.urls]
"Homepage" = "https://github.com/aesedeu/pydrifter"