[build-system]
requires = ["setuptools>=42", "requests"]
build-backend = "setuptools.build_meta"

[project]
name = "process-sanskrit"
version = "1.0.17"  
description = "Process-Sanskrit is python library for automatic Sanskrit text annotation and inflected dictionary search"
readme = "README.md"
authors = [
    {name = "Giacomo De Luca", email = "giacomo.deluca@hotmail.it"}
]
requires-python = ">=3.8"
urls = {Repository = "https://github.com/Giacomo-De-Luca/Process-Sanskrit"}
dependencies = [
    "requests>=2.20.0",
    "sqlalchemy>=1.4.0",
    "indic_transliteration>=2.0.0",
    "regex>=2022.0.0",
    "python-dotenv>=0.19.0",
    "sanskrit-parser==0.2.6",
    "numpy>=2.0.0",           
    "scipy>=1.13.0"           
]

[project.optional-dependencies]
api = [
    "flask>=2.0.0",
    "flask_cors>=3.0.0",
    "openai>=0.27.0",
]
byt5 = [
    "torch>=1.9.0",
    "transformers>=4.5.0",
]
all = [
    "flask>=2.0.0",
    "flask_cors>=3.0.0",
    "openai>=0.27.0",
    "torch>=1.9.0",
    "transformers>=4.5.0"
]

[project.scripts]
update-ps-database = "process_sanskrit.setup.updateDB:update_database"

[tool.setuptools.package-data]
"process_sanskrit.resources" = ["*.json", "*.csv", "*.tsv", "*.xlsx"]
"tests" = ["*.py", "*.json", "*.txt"]

[tool.setuptools]
include-package-data = true