[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "inu"
version = "2.2.3"
description = "Inertial Navigation Utilities"
readme = "README.md"
authors = [
    { name = "David Woodburn", email = "david.woodburn@icloud.com" },
]
license = "MIT"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
requires-python = ">=3.6"
dependencies = [
    "numpy",
    "matplotlib",
    "r3f",
]

[project.urls]
Homepage = "https://gitlab.com/davidwoodburn/inu"
"Bug Tracker" = "https://gitlab.com/davidwoodburn/inu/-/issues"

[tool.setuptools]
package-dir = {"" = "inu"}

[project.optional-dependencies]
test = [
    "pytest",
]
