[build-system]
requires = ["setuptools>=67.0"]
build-backend = "setuptools.build_meta"
[project]
name = "grammateus"
version = "0.0.24"
authors = [
    {name="Alexander Fedotov", email="alex.fedotov@aol.com"},
]
description = "A role similar to a scribe or notary. "
readme = "README.md"
requires-python = ">=3.10"
classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
]
keywords = ["grammateus", "recording", "ai"]
dependencies = [
    "requests >= 2.32.0",
    "jsonlines >= 4.0.0",
    "ruamel.yaml >= 0.18.6",
]
[project.urls]
"Homepage" = "https://github.com/multilogue/grammateus"
"Bug Tracker" = "https://github.com/multilogue/grammateus/issues"