[build-system]
requires = ["setuptools >= 61.0", "numpy"]
build-backend = "setuptools.build_meta"

[project]
name = "zxy9_biomechanical_model"
version = "0.0.4"
authors = [
  { name="Sam Liepke", email="samliepke@gmail.com" },
]
description = "A test package"
dependencies = [
    "numpy",
]

[tool.setuptools.packages.find]
where = ["src"]
