[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"

[project]
name = "wish-sh"
version = "0.6.28"
description = "LLM-assisted shell for penetration testing"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Security & Development Lab", email = "lay.sakura+secdevlab@gmail.com" },
]
maintainers = [
    { name = "Sho Nakatani", email = "lay.sakura@gmail.com" },
]
keywords = [
    "wish",
    "llm",
    "ai",
    "shell",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Software Development :: Libraries",
    "Topic :: System :: Shells",
]
dependencies = [
    "wish-models==0.6.28",
    "textual>=2.1.2",
    "wish-command-execution==0.6.28",
    "wish-command-generation==0.6.28",
    "wish-log-analysis==0.6.28",
    "pydantic>=2.10.6",
    "pydantic-settings>=2.0.0",
]

[project.urls]
Homepage = "https://github.com/SecDev-Lab/wish"
Documentation = "https://github.com/SecDev-Lab/wish"
Repository = "https://github.com/SecDev-Lab/wish.git"
Issues = "https://github.com/SecDev-Lab/wish/issues"

[project.license]
file = "../LICENSE"

[project.scripts]
wish = "wish_sh.wish:main"
wish-sh = "wish_sh.wish:main"

[tool.uv]
dev-dependencies = [
    "factory-boy>=3.3.1",
    "pytest-asyncio>=0.25.2",
    "pytest>=8.3.4",
    "ruff>=0.9.8",
]

[tool.uv.sources.wish-models]
path = "../wish-models"
editable = true

[tool.uv.sources.wish-command-execution]
path = "../wish-command-execution"
editable = true

[tool.uv.sources.wish-command-generation]
path = "../wish-command-generation"
editable = true

[tool.uv.sources.wish-log-analysis]
path = "../wish-log-analysis"
editable = true

[tool.pdm.build]
includes = [
    "src/",
]

[tool.ruff]
line-length = 120
indent-width = 4

[tool.ruff.lint]
select = [
    "E",
    "F",
    "I",
    "B",
    "W",
]

[tool.pytest.ini_options]
testpaths = [
    "tests",
]
pythonpath = [
    "src",
]
addopts = [
    "--import-mode=importlib",
]
asyncio_default_fixture_loop_scope = "function"
